version: '3.0' # the version of docker compose to use

services:
  producer_multi_queue: # define the service
    image: clara690/scraper:${DOCKER_IMAGE_VERSION} # the image & tag to use
    hostname: "job_hunter"
    command: uv run --env-file=.env python -m scraper.producer_multi_queue

    environment:
      - TZ=Asia/Taipei  # set the time zone to Taipei 
    networks:
      - job_network    # connect the service to the network 

networks:
  job_network:
  # join an exising network 
    external: True
