version: '3.0' # the version of docker compose to use

services:
  scraper_104:
    image: clara690/scraper:${DOCKER_IMAGE_VERSION}
    hostname: "job4"
    command: uv run --env-file.env celery -A scraper.worker worker --loglevel=info --hostname=%h -Q 104_jobs
    # restart the container if if breaks down
    restart: always
    environment:
      - TZ=Asia/Taipei
    networks:
      - job_network

  scraper_cake:
    image: clara690/scraper:${DOCKER_IMAGE_VERSION}
    hostname: "cake"
    command: uv run --env-file.env celery -A scraper.worker worker --loglevel=info --hostname=%h -Q cake_jobs

    restart: always
    environment:
      - TZ=Asia/Taipei
    networks:
      - job_network

networks:
  job_network:
    external: true